### ISSUE TITLE
The tutorial content 'Get started with Pipeline API' does not exist.

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#101]
hi, all:
    I can't access this link: `https://alibaba.github.io/pipcook/#/tutorials/get-started-with-pipeline-api`
    Is this page removed?

**Comment by yorkie** [comment]
Sorry, @FeelyChau We have removed the Pipeline APIs at https://github.com/alibaba/pipcook/commit/62ac9184b4627a3ed4c22b9da9afddce66416876, because we introduce a static way to describe the Pipeline: https://github.com/alibaba/pipcook/blob/master/example/pipelines/text-bayes-classification.json.

I will update the TOC for the dead link, thank you :)
