### ISSUE TITLE
meta: may Codespaces of github be used for pipcook?

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#178]
Codespaces, may be a cloud IDE like, one of new features of github, and may Codespaces be used for pipcook?
What will Codespaces do for pipcook, IMO may these:
* Modify pipcook code in cloud but not need to clone local if someone is Experimenter(of cause:)).
* Integrate env of pipcook with Codespaces and make it stable.
* Integrate for plugin developing and make plugin developing easier and convenient.
* Integrate playground for boa and make it easier for experimenting.
* ...

The new features of github are awesome like `GitHub Discussions`、`Code scanning and secret scanning`, may be beneficial if used in pipcook:)

**Comment by yorkie** [comment]
@Txiaozhe Thanks for your suggestions, and GitHub Codespace and others are the beta product that we are not in it's waitlist, and I think this is unrelated about Pipcook's targets, that's great to take a start on one of [the list](https://github.com/alibaba/pipcook/issues?q=is%3Aissue+is%3Aopen+label%3A%22community+driven%22)

**Comment by Txiaozhe** [comment]
OO, I said this for the future:( Thanks

**Comment by yorkie** [comment]
But that's in fact unrelated with Pipcook, they are the features any GitHub project will use. And the Pipcook have discussion about the future architecture(v1.0.0) at https://github.com/alibaba/pipcook/issues/30, otherwise we encourage any new issue is to track the specific problems instead of less relevant suggestions.

**Comment by Txiaozhe** [comment]
OO
