### ISSUE TITLE
training failed，训练cancel 之后训练进程没有退出

### ISSUE THREAD

**Issue by yanuel** [alibaba/pipcook#561]
![image](https://user-images.githubusercontent.com/8894674/92363420-0c8e7200-f124-11ea-80a4-7ed5691f8931.png)

**Comment by yorkie** [comment]
@yanuel 多谢反馈，可以提供一下你使用的 Pipcook 版本，以及 Node.js 版本吗？还有训练用到的 Pipeline。

_Thanks for the feedback, could you please provide the Pipcook versions, Node.js version, and the pipeline that you ran._

**Comment by FeelyChau** [comment]
我想想问题的原因是 costa 用了 IPC 发送 destroy 请求，如果客户端忙碌，比如在执行训练循环，是不会立即退出的。
代码：https://github.com/alibaba/pipcook/blob/master/packages/costa/src/runnable.ts#L175
可能可以用信号代替 IPC 解决这个问题。
I think the reason is: costa send the destroy request by IPC, and if the client is busy, i.e. training loop, it will not exit immediately.
Code: https://github.com/alibaba/pipcook/blob/master/packages/costa/src/runnable.ts#L175
Maybe we should send a signal to instead of IPC.
