### ISSUE TITLE
"Pipcook init" node-gyp rebuild error

### ISSUE THREAD

**Issue by shadowkun** [alibaba/pipcook#99]
When i use node version 10 execute "pipcook init" will got error message:
![image](https://user-images.githubusercontent.com/104660/79411380-4e801580-7fd5-11ea-9280-c66ab704dc8e.png)
I think maybe node version too old to got different API but pipcook not support?

**Comment by yorkie** [comment]
This might be caused by hitting the napi3 at Node10, and we are using napi4. See https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_n_api_version_matrix for the napi version matrix.

**Comment by shadowkun** [comment]
Thx！～～

**Comment by yorkie** [comment]
Reopening because this doesn't get fixed, I'll have a upcoming PR for that :)

**Comment by legendecas** [comment]
Date related N-APIs are available with NAPI_VERSION 5. Node.js v10 LTS line supports NAPI_VERSION 5 after Node.js v10.17.0.

**Comment by shadowkun** [comment]
cool

**Comment by yorkie** [comment]
> Date related N-APIs are available with NAPI_VERSION 5. Node.js v10 LTS line supports NAPI_VERSION 5 after Node.js v10.17.0.

Thanks @legendecas, But boa seems not using the Date N-APIs actually, this issue is to address why do we have a compiler error at node-addon-api, when not given a NAPI_VERSION define, therefore I don't think a newer Node.js version is to help this.

As I have mentioned at https://github.com/nodejs/node-addon-api/pull/703, IMO this might be caused by the wrong condition-macro for NAPI_VERSION checks.
